{
  "formatVersion": "1.1",
  "component": {
    "url": "../../amplify/0.1.0-SNAPSHOT/amplify-0.1.0-SNAPSHOT.module",
    "group": "pro.layne.amps.kmp",
    "module": "amplify",
    "version": "0.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "amplify-iosX64Main-0.1.0-SNAPSHOT.klib",
          "url": "amplify-iosx64-0.1.0-SNAPSHOT.klib",
          "size": 6406,
          "sha512": "84740a8d323005c0f5c5abc3550617568d802f04dcb1b959fd60b14770decf83c87d5e3d5736db5760cfd6b8d61bac22aa9e5de8dae764f6022b8e916f2a6fa3",
          "sha256": "818e787b1b2cd249a79080bb30af5ef596b61a4ddabf310198beae151a8de99d",
          "sha1": "33f85a9e83d744a36c2d8698f9990dc7c8e4fbf9",
          "md5": "e54eb46e5aed5dc383eeb67edf1a9da8"
        },
        {
          "name": "amplify-iosX64Cinterop-AmplifyIosMain-0.1.0-SNAPSHOT.klib",
          "url": "amplify-iosx64-0.1.0-SNAPSHOT-cinterop-AmplifyIos.klib",
          "size": 23434771,
          "sha512": "2df04708c9d7dba65c6d1f0e594a102002f933422d13c82798d1a210ca90a28a6e64f0ad4104beb13b54eae2252c82e3bfa6c5a4524228028cd6df0a7d17e866",
          "sha256": "8403757169ff914e6cc830f786bf2e283ae7bef4e2d48ccdae20c969f3a6ecd5",
          "sha1": "f5298e9a7b1c46424e072758631924d8d8456eec",
          "md5": "ca8d589cae5c49249b6707cb3819c7a8"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "amplify-iosx64-0.1.0-SNAPSHOT-sources.jar",
          "url": "amplify-iosx64-0.1.0-SNAPSHOT-sources.jar",
          "size": 2446,
          "sha512": "5483a10425c175692e5976dcd55242ab55c6556794d8c623190f7d69eda99f1fbbdd432ce4f6f7159b9c2a235837b564ec8ec40823321165d206ebe1f9f82266",
          "sha256": "29689b8935862d74ebd98d1a1f4712b7d4f8d9c9294a184cddd4863b40b95b7a",
          "sha1": "72ed30a657be6f47cf436d7ba9ce7dc70f03210a",
          "md5": "684498fc5955a1e732af4d44308419b5"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "amplify-iosx64-0.1.0-SNAPSHOT-metadata.jar",
          "url": "amplify-iosx64-0.1.0-SNAPSHOT-metadata.jar",
          "size": 23406,
          "sha512": "a98f3d37cdc32e4262a4414197c0b29fb5e4c9cf2e4b57baae7bd9e6f89ef4bbd0de9425755e4b559cd369dd1525e249a3c27413052f7da6bdc73616c3f3e045",
          "sha256": "5bbe87d56a7dea87d70e8b2e818176d18db74c82367d4b1fe3f404218a1b1b3b",
          "sha1": "1e67c0f19c94db46663b964832655f88f976a8e8",
          "md5": "0ed9885f7cdcae331703719759a39551"
        }
      ]
    }
  ]
}
