{
  "formatVersion": "1.1",
  "component": {
    "group": "pro.layne.amps.kmp",
    "module": "shared",
    "version": "0.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "shared-metadata-0.1.0-SNAPSHOT.jar",
          "url": "shared-0.1.0-SNAPSHOT.jar",
          "size": 2786,
          "sha512": "d98e88d180d81900c4bdd5e105a3e0b14e741a1891c9bc299a91fd0f924e08bfae9b3ea2d2078db581df70200436cb3bf1b327b24453abb3791804466789daab",
          "sha256": "7fcd0dcd7f3a5023a9e75501635af1635fce12daae04cc313bf6404d692b7a21",
          "sha1": "f9245d8ca6bfb6da25189034bb4fa6f6bd74f423",
          "md5": "00a57525b59eb2620241e9291691005b"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "shared-kotlin-0.1.0-SNAPSHOT-sources.jar",
          "url": "shared-0.1.0-SNAPSHOT-sources.jar",
          "size": 2556,
          "sha512": "d6240e2bdcd31f60e715ed475a923657aa5c4049f2175db30a9dd45770f3c44ba8a4cc2757dac9c24de636edf143b688e876e47e87994837bf5b224606f56649",
          "sha256": "6f5f39ed806624292da683f172f3ab59960554e41b60f5067f642ca6afdd5244",
          "sha1": "709d7c4b428dce147ac54d75312addf3c9f81d3d",
          "md5": "2e29d15524b0191d07e938cfb845c513"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../shared-iosarm64/0.1.0-SNAPSHOT/shared-iosarm64-0.1.0-SNAPSHOT.module",
        "group": "pro.layne.amps.kmp",
        "module": "shared-iosarm64",
        "version": "0.1.0-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../shared-iosarm64/0.1.0-SNAPSHOT/shared-iosarm64-0.1.0-SNAPSHOT.module",
        "group": "pro.layne.amps.kmp",
        "module": "shared-iosarm64",
        "version": "0.1.0-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../shared-iosarm64/0.1.0-SNAPSHOT/shared-iosarm64-0.1.0-SNAPSHOT.module",
        "group": "pro.layne.amps.kmp",
        "module": "shared-iosarm64",
        "version": "0.1.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../shared-iossimulatorarm64/0.1.0-SNAPSHOT/shared-iossimulatorarm64-0.1.0-SNAPSHOT.module",
        "group": "pro.layne.amps.kmp",
        "module": "shared-iossimulatorarm64",
        "version": "0.1.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../shared-iossimulatorarm64/0.1.0-SNAPSHOT/shared-iossimulatorarm64-0.1.0-SNAPSHOT.module",
        "group": "pro.layne.amps.kmp",
        "module": "shared-iossimulatorarm64",
        "version": "0.1.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../shared-iossimulatorarm64/0.1.0-SNAPSHOT/shared-iossimulatorarm64-0.1.0-SNAPSHOT.module",
        "group": "pro.layne.amps.kmp",
        "module": "shared-iossimulatorarm64",
        "version": "0.1.0-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../shared-iosx64/0.1.0-SNAPSHOT/shared-iosx64-0.1.0-SNAPSHOT.module",
        "group": "pro.layne.amps.kmp",
        "module": "shared-iosx64",
        "version": "0.1.0-SNAPSHOT"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../shared-iosx64/0.1.0-SNAPSHOT/shared-iosx64-0.1.0-SNAPSHOT.module",
        "group": "pro.layne.amps.kmp",
        "module": "shared-iosx64",
        "version": "0.1.0-SNAPSHOT"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../shared-iosx64/0.1.0-SNAPSHOT/shared-iosx64-0.1.0-SNAPSHOT.module",
        "group": "pro.layne.amps.kmp",
        "module": "shared-iosx64",
        "version": "0.1.0-SNAPSHOT"
      }
    }
  ]
}
